name: Publish Package to PyPI
on:
  push:
    branches:
      - production
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Unit Tests
        run: |
          pip3 install pytest streamlit couchbase
          python3 -m pytest cb-streamlit-connector/tests/test_unit.py

      - name: Download the latest release tarball
        run: |
          curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest \
          | grep "browser_download_url.*linux_amd64.tar.gz" \
          | cut -d '"' -f 4 \
          | wget -qi - -O /tmp/git-chglog_linux_amd64.tar.gz

      - name: Extract the tarball
        run: |
          tar -xzf /tmp/git-chglog_linux_amd64.tar.gz -C /tmp

      - name: Move the binary to a directory in your PATH
        run: sudo mv /tmp/git-chglog /usr/local/bin/

      - name: Clean up
        run: rm /tmp/git-chglog_linux_amd64.tar.gz

      - name: Generate Changelog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.4
          # Generate the changelog using git-chglog and store it in a temporary file
          git-chglog -c ./.chglog/config-action.yml -o /tmp/changelog.md 

      - name: Install Hatch
        run: pip install hatch

      - name: Hatch build
        run: hatch build

      - name: Get hatch version
        id: hatch_version_step
        run: echo "VERSION=$(hatch version)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.hatch_version_step.outputs.VERSION }} 
          name: ${{ github.event.commits.message }}
          draft: false
          prerelease: false
          body_path: /tmp/changelog.md
          files: dist/*

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.HATCH_PYPI_TOKEN }}